### ISSUE TITLE
ENH - Pflichtenheft Ergänzen fehlender Kapitel

### ISSUE THREAD

**Issue by HeiwaJan** [SimonSchiebler/my-thai-star#109]
# What needs To Be done?

Das Pflichtenheft um die fehlenden Kapitel ergänzen.

# What Requirement does this Enhancement relate to.

#82 

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by Androx765** [comment]
Timestamp: 3h

**Comment by HeiwaJan** [comment]
Timestamp: 3h
