### ISSUE TITLE
RES - Angular Application

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#11]
# What needs to be researched?
We need more Information on how the Frontend part of the app functions and how it interacts with the Backend service.

https://docs.google.com/document/d/1yRLnOaKlHT4PsKbi3JubXFL1ZZBTTB7Rodqvk9gWMEw/edit#heading=h.chx5fnn3vhz7
## DoD
- [ ] the findings are Documented
- [ ] the team has been Informed about the findings

**Comment by SergejHerwald** [comment]
12.04.2021 
Sergej:
AngularJs: 3 Stunden
Typescript: 1.5 Stunden

**Comment by SergejHerwald** [comment]
13.04.2021
Typescript: 5 hours spent (done)
AngularJs: 2 hours spent

**Comment by SergejHerwald** [comment]
14.04.2021
Angular: 7 hours spent

**Comment by Androx765** [comment]
Angular basics 
Timestamp: 6h

**Comment by Androx765** [comment]
Angular in relation to App
Timestamp: 3h

**Comment by Androx765** [comment]
getting more information not directly related to Angular
Timestamp: 2h

**Comment by SergejHerwald** [comment]
15.04.2021
Angular
Timestamp: 3h

**Comment by SergejHerwald** [comment]
16.04.2021
Angular tutorials / Angular in relation to App
Timestamp: 12h
