### ISSUE TITLE
ENH - Überarbeitung Lastenheft

### ISSUE THREAD

**Issue by HeiwaJan** [SimonSchiebler/my-thai-star#111]
# What needs To Be done?

Durch den Kunden angeforderte Überarbeitungen des Lastenheft umsetzen.

# What Requirement does this Enhancement relate to.

#14 

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by SimonSchiebler** [comment]
not required anymore
