### ISSUE TITLE
RES - Java Spring

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#12]
# What needs to be researched?

https://docs.google.com/document/d/1g2vMuxORKKvD8QkW3PnOJAhZAT3VK1ySSwyBj93jsbs/edit#
## DoD
- [ ] the findings are Documented
- [ ] the team has been Informed about the findings

**Comment by SimonSchiebler** [comment]
https://www.youtube.com/watch?v=gq4S-ovWVlM

**Comment by SimonSchiebler** [comment]
official docs for this part
https://devonfw.com/website/pages/docs/master-my-thai-star.asciidoc_technical-design.html#master-my-thai-star.asciidoc_server-side

**Comment by SimonSchiebler** [comment]
docs relevant for testing
https://github.com/devonfw/my-thai-star/wiki/java-testing

**Comment by SimonSchiebler** [comment]
found the DB that is used within this Project:
https://www.h2database.com/html/main.html

I found this information in the application.properties
mtsj\core\src\main\resources

**Comment by HeiwaJan** [comment]
3,5h (12.04)

**Comment by HeiwaJan** [comment]
3h (13.04)

**Comment by SimonSchiebler** [comment]
Official Devonfw docs for the java backend
https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html

**Comment by SimonSchiebler** [comment]
Timestamp: 5h

**Comment by SimonSchiebler** [comment]
Timestamp: 4h

**Comment by HeiwaJan** [comment]
https://docs.spring.io/spring-framework/docs/current/javadoc-api/overview-summary.html
