### ISSUE TITLE
REQ - Lastenheft

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#14]
## Description
This Document will contain all Requirements for our Project. 
https://docs.google.com/document/d/1oi8zxZflTrUaUyPII71jFy8lp3ksWjv1U5c-h_rPGro/edit

This Research Task describes how it should be written
https://github.com/SimonSchiebler/my-thai-star/issues/6

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] All subfeatures are ready
- [ ] Estimated

## DoD
- [ ] All linked Features are done
- [ ] Requirement is documented in the User Documentation

**Comment by SimonSchiebler** [comment]
10h

**Comment by SimonSchiebler** [comment]
2h

**Comment by SimonSchiebler** [comment]
Timestamp: 2h

**Comment by HeiwaJan** [comment]
Timestamp: 1h

**Comment by SimonSchiebler** [comment]
Timestamp: 2h
