### ISSUE TITLE
FEA - Connect AdminUI to the Backend

### ISSUE THREAD

**Issue by SergejHerwald** [SimonSchiebler/my-thai-star#140]
# What needs To Be done?

# What Requirement does this Feature relate to.

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by SergejHerwald** [comment]
12.05.2021
Timestamp: 4h

**Comment by SergejHerwald** [comment]
12.05.2021
Timestamp: 8h

**Comment by SergejHerwald** [comment]
13.05.2021
Timestamp: 8h

**Comment by SergejHerwald** [comment]
Timestamp: 8h

**Comment by SimonSchiebler** [comment]
Timestamp: 1h
