### ISSUE TITLE
BUG - Information disclousure, password plaintext storage

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#19]
Original Issue:
https://github.com/devonfw/my-thai-star/issues/55

**Comment by SimonSchiebler** [comment]
Previous commits seem to have fixed this bug. The passwords are now encrypted with Bcrypt. We will have to do some further testing to confirm this.

**Comment by SimonSchiebler** [comment]
The passwords are hashed on the server side. Changing this behaviour to client side hashing would probably be out of scope.

**Comment by SimonSchiebler** [comment]
1,5h

**Comment by HeiwaJan** [comment]
1,5h

**Comment by SimonSchiebler** [comment]
Closing this issue because it has already been fixed
