### ISSUE TITLE
REQ - take delivery orders 

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#24]
## Description
The Alexa@home skill needs a way for a user to submit a delivery order. The skill will need to ask the user for an address and delivery time and date.

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] All subfeatures are ready
- [ ] Estimated

## DoD
- [ ] All linked Features are done
- [ ] Requirement is documented in the User Documentation

**Comment by Androx765** [comment]
![SetTime](https://user-images.githubusercontent.com/37586467/115114723-09e4dc80-9f91-11eb-9951-282a6276067d.png)
[#28 ](https://github.com/SimonSchiebler/my-thai-star/issues/28)
