### ISSUE TITLE
REQ - Call Waiter

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#26]
## Description
The inhouse alexa skill needs a function to call a waiter.
This would probably be easy to implement as its own state that can be displayed in the waiter cockpit.

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] All subfeatures are ready
- [ ] Estimated

## DoD
- [ ] All linked Features are done
- [ ] Requirement is documented in the User Documentation

**Comment by HeiwaJan** [comment]
![inform_waiter](https://user-images.githubusercontent.com/82204719/115113417-86c08800-9f8a-11eb-9b51-ddf105db9249.png)
