### ISSUE TITLE
REQ - Asking for the check

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#27]
## Description
The inhouse Alexa skill needs to offer a way to ask for the check.
This would probably be easy to implement as its own state that can be displayed in the waiter cockpit.

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] All subfeatures are ready
- [ ] Estimated

## DoD
- [ ] All linked Features are done
- [ ] Requirement is documented in the User Documentation

**Comment by SergejHerwald** [comment]
![image](https://user-images.githubusercontent.com/61739218/115114461-d5245580-9f8f-11eb-9966-ab1542c1b850.png)

**Comment by SergejHerwald** [comment]
%3CmxGraphModel%3E%3Croot%3E%3CmxCell%20id%3D%220%22%2F%3E%3CmxCell%20id%3D%221%22%20parent%3D%220%22%2F%3E%3CmxCell%20id%3D%222%22%20value%3D%22Ask%20for%20a%20bill%22%20style%3D%22rounded%3D1%3BwhiteSpace%3Dwrap%3Bhtml%3D1%3B%22%20vertex%3D%221%22%20parent%3D%221%22%3E%3CmxGeometry%20x%3D%22480%22%20y%3D%2240%22%20width%3D%22105%22%20height%3D%2250%22%20as%3D%22geometry%22%2F%3E%3C%2FmxCell%3E%3C%2Froot%3E%3C%2FmxGraphModel%3E

**Comment by SergejHerwald** [comment]
https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R5VjbcpswEP0aPzZjwGDn0SaXzrSd6dQPaR5l2IAagagQAfr1XRlhgXGcdHLB0zzYwx502T17tEKaOH5SXQuSxd94CGxiT8Nq4lxMbHvhufivgLoBZgunASJBwwayDLCmf0CDU40WNIS811ByziTN%2BmDA0xQC2cOIELzsN7vjrD9rRiIYAOuAsCF6Q0MZ67DsucE%2FA43idmbLO2%2FeJKRtrCPJYxLysgM5lxPHF5zL5impfGCKu5aXpt%2FVI293jglI5XM6rH58Keo4uC7nAtY3v%2F3bqZd%2Fap17IKzQEZcUHUemBIU0zLXvsm4JkVDhdKtYJgwBCx9zKfg9%2BJxxgUjKU2y5uqOM7UGE0ShFM0CHAfHVAwhJkeqlfpHQMFTTrMqYSlhnJFBzlqgrxAQv0hBULFO0tNc4AFSP8mHtWEZ1Ak9AihqbtB0cHbtWpuVpuzR5nmko7qS4pYxoZUW7kQ35%2BKD5%2F4dctMrpkA0hilGbXMiYRzwl7NKge7SYNl85z3R%2BfoGUtV5ZpJC8nz1kS9Q%2FVf8ztzVv9XBb46LqWXUvA8rB4%2FxjPLwQARwJ3NUlQRIRgTzGkHs4owIYkfSh78mr56d1s7NWlvn9tqgINR%2F%2BNlQNs5dEkyLrEW130vEKwnb7uraHsram7lDX7pvp2hpQ8kF0PX%2BurqeHE%2FpOup4PdL0GjJdIYDi6RxKl0XSTZ9tMbHdgjCdWNfzq1NRunY8u99kHlXu7fz4td2dMuXvDTx6fiBCRrbYDkscnqGt7Mbquh9ufz9M7KpJT48qZj86VN0oNqKjslAC0bjtvTAFQRrv%2BT6FuuM%2BsG81GNVrdmI9b13vZMck6ofy8%2BDNm23UpBKk7DTJOU5l3Rv6uALP4949xzt4x%2BHhzR9cFo4xmfqOTXSAvkI47KJ1Lpg7Fes%2FZO3If2n1inmyK%2FF2qqWefuT2ODnxSLQ4cjBdvVk0XA%2FpIQ9%2F%2Fejcxe7erCTTNFVSjd3OP51z%2BBQ%3D%3D

**Comment by SergejHerwald** [comment]
![Untitled Diagram (2)](https://user-images.githubusercontent.com/61739218/115114737-24b75100-9f91-11eb-8052-09488234c765.jpg)
