### ISSUE TITLE
REQ - Taking orders

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#28]
## Description
The alexa skill needs a way to take an order. Making this process intuitive is very important. Simply listing every item on the menu will not make for a good user experience.

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] All subfeatures are ready
- [ ] Estimated

## DoD
- [ ] All linked Features are done
- [ ] Requirement is documented in the User Documentation

**Comment by SimonSchiebler** [comment]
![order](https://user-images.githubusercontent.com/32509205/115112572-6989ba80-9f86-11eb-9bdd-1013d8300ea3.png)

**Comment by Androx765** [comment]
![Take-Orders](https://user-images.githubusercontent.com/37586467/115113200-765bdd80-9f89-11eb-9f0a-24afaa6b2571.png)
