### ISSUE TITLE
REQ - Order States

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#36]
An order should have these states 

ordered > in preparation > pending delivery > Delivered

These states are inspired by dominos delivery service:
![image](https://user-images.githubusercontent.com/32509205/115108688-19086200-9f72-11eb-8bd9-4f7d125f5e16.png)

Here we would not implement the rating step.

This order state should be editable in the waiter cockpit and be visible for the customer

**Comment by SergejHerwald** [comment]
Timestamp: 0.5h
