### ISSUE TITLE
REQ - Edit order state

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#38]
![image](https://user-images.githubusercontent.com/32509205/115109232-c9776580-9f74-11eb-904b-d98c1d0e6280.png)
The order states should be editable in the order cockpit

**Comment by SergejHerwald** [comment]
Prototype:
![image](https://user-images.githubusercontent.com/61739218/115213882-44ba5200-a102-11eb-9b7e-2b3ab55fc53c.png)
Timestamp: 1h
