### ISSUE TITLE
RES - getting started DevonFW

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#5]
# What needs to be researched?

We need a tutorial on how to setup DevonFW locally and how to run the Application in this Repo. Also it would be great if the Presentation would also contain Use Cases for devonFW.

## DoD
- [ ] the findings are Documented
- [ ] the team has been Informed about the findings

**Comment by SimonSchiebler** [comment]
4h

**Comment by Berndow** [comment]
Timestamp: 2h
