### ISSUE TITLE
RES - Lastenheft

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#6]
# What needs to be researched?
We will need to know what exactly a "Lastenheft" is and what it should contain.

## DoD
- [x] the findings are Documented
- [x] the team has been Informed about the findings

**Comment by Androx765** [comment]
so its just a guideline on how to create a "lastenheft", and not our final submission right?

**Comment by Androx765** [comment]
pdf im OneDrive

**Comment by SimonSchiebler** [comment]
https://drive.google.com/drive/folders/1XkhC34ePBoEb93zcLjGMq4LsqHXuJUCX

**Comment by Androx765** [comment]
New Link:
https://drive.google.com/drive/folders/1rv-rSiT4HK7fdGfhytA9a9-DF2-9xlO_

**Comment by SimonSchiebler** [comment]
neuer link
https://docs.google.com/document/d/10njSoc5HnSsZwNts9kOMKbWtfLVaAks4URrA5Rh3LzQ/edit

**Comment by Androx765** [comment]
Timestamp: 3h
