### ISSUE TITLE
ORG - Jours Fixe #1 Presentation

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#63]
https://docs.google.com/presentation/d/1LSggAdjdS9HZV1UHJv3NU_R7i-pu8GUIdPA5SIaHoH0/edit#slide=id.p

**Comment by SimonSchiebler** [comment]
Timestamp: 4h

**Comment by SimonSchiebler** [comment]
Timestamp: 4.25h

**Comment by SimonSchiebler** [comment]
Presentation
Timestamp: 6.5h

**Comment by Androx765** [comment]
Presentation
Timestamp: 6.5h

**Comment by Berndow** [comment]
6.5h

**Comment by SergejHerwald** [comment]
Timestamp: 6.5h

**Comment by HeiwaJan** [comment]
Timestamp: 6.5h
