### ISSUE TITLE
FEA - Rest parameters for state filtering of orders

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#72]
# What needs To Be done?
to display orders in the waiter cockpit our rest endpoint will need the capability to accept an order state as a filter parameter.

# What Requirement does this Enhancement relate to.
https://github.com/SimonSchiebler/my-thai-star/issues/36

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by HeiwaJan** [comment]
Timestamp: 2.75h

**Comment by SimonSchiebler** [comment]
Timestamp: 2,75h

**Comment by Berndow** [comment]
Timestamp: 2.75h
