### ISSUE TITLE
FEA - Order Archive

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#73]
# What needs To Be done?
The angular application needs a seperate tab to display all orders with the states "canceled" and "deliveres"

# What Requirement does this Enhancement relate to.
https://github.com/SimonSchiebler/my-thai-star/issues/37
## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by Androx765** [comment]
Timestamp: 4h

**Comment by Androx765** [comment]
Timestamp: 2h

**Comment by Androx765** [comment]
Timestamp: 3h

**Comment by SimonSchiebler** [comment]
Timestamp: 3h

**Comment by Androx765** [comment]
Timestamp: 5h

**Comment by Androx765** [comment]
Timestamp: 0.5h
