### ISSUE TITLE
FEA - Order States Tab in waiter cockpit order view

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#74]
# What needs To Be done?
The order states should be displayed for each order as required in #36 
Each change should fire a rest request against the java backend to update the state.

# What Requirement does this Enhancement relate to.
https://github.com/SimonSchiebler/my-thai-star/issues/36

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by SergejHerwald** [comment]
19.04.2021:
Timestamp: 3h

**Comment by SergejHerwald** [comment]
20.04.2021:
Timestamp: 3h

**Comment by SergejHerwald** [comment]
Timestamp: 2h

**Comment by SergejHerwald** [comment]
Timestamp: 4h

**Comment by HeiwaJan** [comment]
Timestamp: 2h

**Comment by SimonSchiebler** [comment]
Timestamp: 6h

**Comment by SergejHerwald** [comment]
Timestamp: 6h
