### ISSUE TITLE
FEA - Add states property to order entity

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#77]
# What needs To Be done?
The order entity needs a property for the state to be stored in. 

# What Requirement does this Enhancement relate to.
#36

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by HeiwaJan** [comment]
Timestamp: 5h
