### ISSUE TITLE
ENH - Website

### ISSUE THREAD

**Issue by SimonSchiebler** [SimonSchiebler/my-thai-star#8]
# What needs To Be done?
The website needs some more styling and our images.

# What Requirement does this Enhancement relate to.

## DoR
- [x] Prioritized
- [x] Clearly Written
- [x] Contains all specifications
- [x] Free from external Dependencies
- [x] Estimated

## DoD
- [x] All code is written
- [x] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [x] Build has been made and deployed (on a testing environment).

**Comment by SimonSchiebler** [comment]
https://moodle.hs-mannheim.de/mod/wiki/view.php?id=153505

**Comment by SimonSchiebler** [comment]
page is available at:
https://bitshift-team.de/

**Comment by SimonSchiebler** [comment]
Time Spent
14h

**Comment by SergejHerwald** [comment]
Time spent: 15h

**Comment by SimonSchiebler** [comment]
Documentation not really necessary because the website is nor part of the final product
