### ISSUE TITLE
FEA - Alexa Backend Logic

### ISSUE THREAD

**Issue by HeiwaJan** [SimonSchiebler/my-thai-star#84]
# What needs To Be done?

Implement a backend logic that allows Alexa to communicate with the backend.

# What Requirement does this Feature relate to.

#67 

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by SimonSchiebler** [comment]
Timestamp: 10h

**Comment by HeiwaJan** [comment]
Timestamp: 2h
