### ISSUE TITLE
FEA - Alexa Skill

### ISSUE THREAD

**Issue by HeiwaJan** [SimonSchiebler/my-thai-star#85]
# What needs To Be done?

Implement a first basic Alexa Skill that allows it to post something into the Data.

# What Requirement does this Feature relate to.

#67

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by SimonSchiebler** [comment]
Timestamp: 7.5h

**Comment by HeiwaJan** [comment]
Timestamp: 7h

**Comment by HeiwaJan** [comment]
Timestamp: 7h

**Comment by SimonSchiebler** [comment]
Timestamp: 7.5h

**Comment by SimonSchiebler** [comment]
Timestamp: 7h
