### ISSUE TITLE
FEA - Preview Pflichtenheft (Introduction)

### ISSUE THREAD

**Issue by HeiwaJan** [SimonSchiebler/my-thai-star#89]
# What needs To Be done?

Write the Introduction for the Pflichtenheft.

# What Requirement does this Feature relate to.

#82 

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by SimonSchiebler** [comment]
Timestamp: 4h

**Comment by HeiwaJan** [comment]
Timestamp: 2h

**Comment by SergejHerwald** [comment]
Timestamp: 2h
