### ISSUE TITLE
FEA - Admin UI Frontend

### ISSUE THREAD

**Issue by HeiwaJan** [SimonSchiebler/my-thai-star#97]
# What needs To Be done?

Design and implement the Frontend for the Admin UI.

# What Requirement does this Enhancement relate to.

#96 

## DoR
- [ ] Prioritized
- [ ] Clearly Written
- [ ] Contains all specifications
- [ ] Free from external Dependencies
- [ ] Estimated

## DoD
- [ ] All code is written
- [ ] Code review has been completed.
- [ ] Code is documented.
- [ ] Code is tested and tests have passed.
- [ ] Build has been made and deployed (on a testing environment).
- [ ] Time has been recorded

**Comment by SergejHerwald** [comment]
Timestamp: 9.0h

**Comment by Androx765** [comment]
Timestamp: 3.0h

**Comment by SergejHerwald** [comment]
Timestamp: 2.0h

**Comment by SergejHerwald** [comment]
Timestamp: 1.0h

**Comment by Androx765** [comment]
Timestamp: 6h

**Comment by Androx765** [comment]
Timestamp: 1.5h

**Comment by Androx765** [comment]
Timestamp: 2h

**Comment by Androx765** [comment]
Update Concept: 
If delete button is pressed, poppup will show up, if pressed again user could be moved into sort of tash-can.

**Comment by SergejHerwald** [comment]
30.04.2021
Timestamp: 2h

**Comment by Androx765** [comment]
Timestamp: 8h
